### ISSUE TITLE
[QUESTION] PHP/Laravel formato

### ISSUE THREAD

**Issue by allanbarbosa** [lucassmacedo/cbo-brasil#1]
Olá, bom dia.
Estou querendo contribuir com o projeto e gostaria de tirar uma dúvida.

Quando você fala "Criar o Formato PHP/Laravel (Migrations and Seed)" você está querendo um código que leia os arquivos nos formatos estipulados e retorne a resposta?

Queria entender melhor para contribuir.

Abraços,

**Comment by lucassmacedo** [comment]
Olá @allanbarbosa Grato pelo interesse! Não necessariamente, pensei em criar as migrations com a estrutura do banco de dados, de acordo com os arquivos e os seed apenas para inserir esses dados. 
Mas é apenas uma idéia, aceito sugestões. Se tiver disposição podemos até pensar em criar uma API ou algo do tipo.

**Comment by allanbarbosa** [comment]
Posso contribuir com todas as ações, acho que nesse caso seria interessante construir uma API para publicarmos e o povo consultar para obter a listagem.
Como você irá atualizar esses arquivos caso tenha novas inclusões de CBO?

**Comment by lucassmacedo** [comment]
@allanbarbosa a ultima atualização foi em 2016, o site do ministério do trabalho gera o arquivo de atualização por ano, se for o caso podemos escrever uma rotina que atualize os dados, mas parece haver algum problema no site.. não da certo baixar o arquivo.
http://www.mtecbo.gov.br/cbosite/pages/DownloadHistorico.jsf
Mas em todo caso, vou iniciar um projeto em L5.5 com a estrutura basica de uma api e compartilho com você

**Comment by allanbarbosa** [comment]
Beleza, no aguardo.

**Comment by lucassmacedo** [comment]
@allanbarbosa enviei o convite, depois me passa seu contato para conversamos melhor.

**Comment by ghost** [comment]
Senhores, boa noite! 

Também tenho interesse!

Não sei se vocês conhecem, mas o governo disponibiliza um [kit de dados abertos](http://kit.dados.gov.br/). Nele da pra ter uma base legal sobre conceitos, ferramentas, legislação e etc.

Quanto aos diversos tipos de arquivos como fontes de dados, temos o [OpenRefine](http://openrefine.org/), nele podemos podemos unificar e minerar os dados independente do tipo de arquivo e exportá-los em um único arquivo.

Vamos começar? rsrs

**Comment by lucassmacedo** [comment]
Opa! Legal @lucastimotio mto boa essa informação! Vamos sim! Pensei em criar um grupo para melhor conversarmos o que acham?
@lucastimotio @allanbarbosa 
Pode ser telegram, slack, whats, fb .. etc.
Penso que podemos fazer um projeto bem legal com esses dados

**Comment by allanbarbosa** [comment]
Bem, é só você criar ai. Prefiro Telegram ou Slack.

**Comment by ghost** [comment]
Slack!

**Comment by lucassmacedo** [comment]
Vocês estão no Laravel BR? Podemos criar umprivate  channel lá

**Comment by ghost** [comment]
Add lá, lucastimotio@gmail.com

**Comment by allanbarbosa** [comment]
Pode me adicionar também: allan.frb@gmail.com

**Comment by lucassmacedo** [comment]
Enviado

**Comment by allanbarbosa** [comment]
Aceito.

**Comment by ghost** [comment]
Não recebi!

**Comment by ghost** [comment]
Não tinha visto... Aceito!

**Comment by lucassmacedo** [comment]
@lucastimotio pronto! voce ta no channel agora

**Comment by luandiego7** [comment]
opa.. e aí pessoal. Boa tarde! Tudo bem com vcs ? 
Por esses dias precisei de um seeder dos cbo's, pesquisei no google e achei aqui.. 
Como anda o projeto? Conseguiram finalizar? Não achei o seeder e tal... 
Enfim, eu fiz aqui um seeder, bem rápido e tranquilo. 
Em uma empresa que trabalhei, eles tinha uma tabela já com todos os cbo's inseridos. 
Então, baixei essa tabela em xml, e usando o replace(usei o phpstorm, mas poderia ser no sublime ou qualquer outro editor de texto), substituí certinho, criando a estrutura de um seeder. Foi mt rápido e tranquilo. Menos de 1minuto tava pronto kkkk 
Já tava triste e preocupado, pensando em como ia fazer um seeder com mais de 2600 registros.. na mão. Pqp kkkk. 
Quem ainda tiver interesse, está nesse repositório: https://github.com/luandiego7/cbo-seeder
Qualquer coisa estamos aí. 
Abraços.
