### ISSUE TITLE
Converter charset para UTF-8

### ISSUE THREAD

**Issue by robertopc** [lucassmacedo/cbo-brasil#2]
Recomendo converter para o charset UTF-8.
Pois é um padrão utilizado pela maioria dos sistemas hoje em dia.

**Comment by lucassmacedo** [comment]
@robertopc se quiser contribuir com essa conversão, fico agradecido!

**Comment by robertopc** [comment]
PR enviado

**Comment by lucassmacedo** [comment]
Valeu @robertopc  já fiz o merge!
